spring:
  application:
    name: madis-paymentgateway-service
  eureka:
    client:
      service-url:
      # Replace with the address of your Eureka server
        defaultZone: ${EUREKA_SERVER:https://render-ereuka.onrender.com}
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 30
      metadata-map:
        instanceId: ${spring.application.name}:${server.port}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-crp8ipjtq21c7397k1g0-a.oregon-postgres.render.com:5432/madisdb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USR:madisdev}
    password: ${DATABASE_PWD:9yTA0MC77iRjGrY6Y1F86ulAXkaQVfcr}
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: false

  cloud:
    loadbalancer:
      health-check:
        enabled: true # Ensure LoadBalancer is using Consul's health check
    # consul:
    #   enabled: true
    #   uri: ${CONSUL_HOST:https://render-consul.onrender.com/}
    #   #host: ${CONSUL_HOST:216.24.57.4}
    #   #port: ${CONSUL_PORT:8500}
    #   config:
    #     enabled: true
    #   discovery:
    #     enabled: true
    #     service-name: madis-paymentgateway-service
    #     prefer-ip-address: true
    #     heartbeat:
    #       enabled: true
info:
  app:
    name: ${spring.application.name}

header:
  hub2:
    baseurl: https://api.hub2.io
    currency: XOF
    businessname: MADIS-WALLET
    transfer:
      create: ${header.hub2.baseurl}/transfers
      retrieve: ${header.hub2.baseurl}/transfers/%s
      status: ${header.hub2.baseurl}/transfers/status
    payment:
      intent: ${header.hub2.baseurl}/payment-intents
      attempt: ${header.hub2.baseurl}/payment-intents/%s/payments
      retrieve: ${header.hub2.baseurl}/payment-intents/%s
      retrieveall: ${header.hub2.baseurl}/payment-intents
    apikey: sk_vvAi129W8ij8WJwf4U5kKNo1QGJAmcbK #sk_RNUu2trAJDRKaAZURotWzwxrVFSr4omu
    merchantid: 1wnHrHqoKjGMGXQWzLWt6
    environment: sandbox

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  discovery:
    enabled: true # Enables Feign to use Consul for service discovery

springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs # OpenAPI docs endpoint for this service
  swagger-ui:
    path: /swagger-ui.html # Swagger UI for this service

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors.allowed-origins: true

logging:
  level:
    root: ERROR
    com.madisfinance.paymentgatewayservice: INFO
    org.springframework.web: ERROR
server:
  address: 0.0.0.0
  port: ${PORT:8081}
